nginx/nginx-s3-gateway

Dockerfile.oss, Dockerfile.plus, common/etc/nginx/include/s3gateway.js, common/etc/nginx/nginx.conf, common/etc/nginx/templates/default.conf.template, plus/usr/local/bin/add_nginx_plus_repo.sh, test/docker-compose.yaml, test/unit/s3gateway_test.js
This change upgrades NGINX to 1.19.7 and NJS to 0.5.1.
In this new version of NJS, it provides a filter function
that allows for headersOut to be modified thereby removing
the need for the headers_more module to strip off x-amz
headers.
=> Updated to use latest NGINX and NJS

common/etc/nginx/include/s3gateway.js
I was getting `SignatureDoesNotMatch` errors when using directory
listing with v4 authentication. Seems like the problem was
the requests were sent with trailing `/` while the signature
was calculated without it.
It doesn't seem we need the trailing space there (I have checked
only with Ceph S3 API, so more testing with AWS welcome), but seems
like the code should be broken for every back-end, unless I'm missing
something.
=> Fix auth v4 for directory listing

common/etc/nginx/include/s3gateway.js, docs/getting_started.md
The appropriate STS endpoint gets detected via the `AWS_STS_REGIONAL_ENDPOINTS` and `AWS_REGION` env variables.
This change is untested as I don't have an environment available for testing currently.
=> Support for regional STS endpoint detection

.github/workflows/main.yml
Signed-off-by: jongwooo <jongwooo.han@gmail.com>
Resolve  #94 
Update `.github/workflows/main.yml` to use environment file instead of deprecated `set-output` command. 
For more information, see: [https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/)
I found the workflow files that use `set-output` command through the following command:
```bash
$ find . -name '*.yml' -o -name '*.yaml' | xargs egrep '\bset-output\b'
```
**AS-IS**
```yml
run: echo "::set-output name=date::$(date +'%Y%m%d')"
```
**TO-BE**
```yml
run: echo "date=$(date +'%Y%m%d')" >> $GITHUB_OUTPUT
```
=> Replace deprecated command with environment file

standalone_ubuntu_oss_install.sh
**Problem:**
- When running `standalone_ubuntu_oss_install.sh` for `nginx-s3-gateway` as a Systemd Service, the following error occurs:
```bash
standalone_ubuntu_oss_install1.sh: line 224: /etc/systemd/system/nginx.service.d/override.conf: No such file or directory
```
- Root-cause: `/etc/systemd/system/nginx.service.d/` does not exist.
**Fix:**
- Create a directory of `etc/systemd/system/nginx.service.d/` prior to running the following script:
```
cat > /etc/systemd/system/nginx.service.d/override.conf << 'EOF'
[Service]
EnvironmentFile=/etc/nginx/environment
ExecStartPre=/usr/local/bin/template_nginx_config.sh
EOF
```
=> Fix no such directory for nginx.service.d

docs/getting_started.md
This is to fix the name of container in the doc of `Building the NGINX Plus Container Image`.
**Fix-1**
- As-Is: `docker build --file Dockerfile.oss --tag nginx-s3-gateway --tag nginx-s3-gateway:latest-njs-plus .`
- To-Be: `docker build --file Dockerfile.plus --tag nginx-plus-s3-gateway --tag nginx-plus-s3-gateway:latest-njs-plus .`
**Fix-2**
- As-Is: `docker run ... --name nginx-s3-gateway \
nginx-s3-gateway:plus`
- To-Be: `docker run ... --name nginx-plus-s3-gateway \
nginx-plus-s3-gateway:plus`
=> Fix typo: nginx-s3-gateway -> nginx-plus-s3-gateway 

common/etc/nginx/include/s3gateway.js
At least in Fargate, the instance role credentials have a human-readable expiration time, not a unix timestamp (for example - `'2023-02-25T19:56:26Z'`).
As a result, we get `NaN` when multiplying this value by 1000 which breaks the expiry checking logic. This leads to credentials being fetched on every request, which is slow and may well exceed the limits of the metadata endpoint.
My proposed solution is to only do the multiplication if our expiration time is numeric, on the assumption that this must be true in some contexts. `Date` can accept the string expiration times directly with no additional processing.
I've only tested this in Fargate - it might be worth ensuring that this still works for credentials in other contexts.
=> Bugfix: Handle non-unixtime expiration

common/docker-entrypoint.d/00-check-for-required-env.sh
Fixing edgecase. Add maximum execution time to curl for prevent inifinity wait resolve tarpited (dropped) request.
=> Fix edge-case with firewall tarpit

common/etc/nginx/templates/default.conf.template
When file not exist in s3 nginx return 404 response without CORS headers.
=> Add missing CORS headers for 404 status code

docs/development.md, test.sh
Small changes to the documentation and test runner comments to improve the integration test writing experience.
Changes:
1. Clarified the name of the minio tool required since it took a few minutes of searching
2. Documented the purpose and acceptable values of the many params to the integration test runner function
=> chore: small fixes to test scripts and README for clarity

docs/development.md, test.sh, test/integration/test_api.sh
Fix error messages for missing dependencies, allow test suite to run on MacOS by supporting `md5`
There were some checks like this:
```bash
curl_cmd="$(command -v curl)"
if ! [ -x "${curl_cmd}" ]; then
e "required dependency not found: curl not found in the path or not executable"
exit ${no_dep_exit_code}
fi
```
However, `command -v` exits with an error if the command does not exist. This results in the nice error message not being shown.
The solution is to avoid the assignment of the variable erroring and instead relying on the executability check to make sure we have the right thing
The test script depends on `md5sum` which is not available on MacOS. Thus, tests would fail at the start when run on MacOS.
MacOS has a tool called `md5`, which when called with the `-r` flag which reverses …
=> Fix error messages for missing dependencies, allow test suite to run on MacOS by supporting `md5`

common/docker-entrypoint.sh
Fixes an issue where comments in the `/etc/resolv.conf` would get into the dns resolvers list and cause an error when starting the s3 gateway.
Following a suggestion on the issue, the logic from [this file](https://github.com/nginxinc/docker-nginx/blob/master/entrypoint/15-local-resolvers.envsh) in the official NGINX docker container was ported over to replace the existing logic.
Given a `/etc/resolv.conf` that looks like this:
```
nameserver 127.0.0.11
nameserver 8.8.4.4
nameserver 94.198.184.14
nameserver 94.198.184.34
nameserver 8.8.8.8
options ndots:0
```
The existing code would produce this:
```
127.0.0.11 8.8.4.4 94.198.184.14 94.198.184.34 [NOTE:] The 8.8.8.8
```
With this change applied it looks like this:
```
127.0.0.11 8.8.4.4 94.198.184.14 94.198.184.34 8.8.8.8
```
The startup …
=> fix: gracefully handle comments in resolv.conf. Fixes #171

common/etc/nginx/include/awssig4.js, test/unit/awssig4_test.js
As writing in [Signature Calculations for the Authorization Header: Transferring Payload in a Single Chunk (AWS Signature Version 4)](https://docs.aws.amazon.com/AmazonS3/latest/API/sig-v4-header-based-auth.html)
> The x-amz-content-sha256 header is required for all AWS Signature Version 4 requests. It provides a hash of the request payload. If there is no payload, you must provide the hash of an empty string.
> For the purpose of calculating an authorization signature, only the host and any x-amz-* headers are required;
We should add x-amz-content-sha256 to CanonicalHeaders
=> Add x-amz-content-sha256 to CanonicalHeaders

common/docker-entrypoint.d/00-check-for-required-env.sh
=> fix: handle IMDSv2 auth when checking if we are running on EC2 instance

.github/workflows/main.yml, test.sh
Allows us to push multi-architecture builds for `linux/amd64` and `linux/arm64` on merge to master. Fixes: https://github.com/nginxinc/nginx-s3-gateway/issues/196
The flow looks like this:
```
┌──────────────────┐        ┌────────────────┐      ┌────────────────┐
┌─────────┐     ┌─────────┬────► Build Latest NJS ├────────►Test Latest NJS ├─────►│Push Latest NJS │
│Build OSS├────►│Test OSS │    └──────────────────┘        └────────────────┘      └────────────────┘
└─────────┘     └──┬──────┤
│      │    ┌──────────────────┐       ┌──────────────────┐     ┌─────────────────┐
│      └────►Build Unprivileged├───────►Test Unprivileged ├────►│Push Unprivileged│
│           └──────────────────┘       └──────────────────┘     ├────────┬────────┘
│ …
```
=> Build multi-architecture images

.github/workflows/main.yml
The original pull request https://github.com/nginxinc/nginx-s3-gateway/pull/197 had an issue where the final build and push could not find the base image locally.
This change corrects the issue but introducing a local registry to the final build push step as described in https://docs.docker.com/build/ci/github-actions/named-contexts/#using-with-a-container-builder since the `docker-container` driver-based build can't load from the local docker environment.
=> fix and issue where final build cannot find the base image for build

common/etc/nginx/templates/default.conf.template
As reported here https://github.com/nginxinc/nginx-s3-gateway/issues/205 when 
* `APPEND_SLASH_FOR_POSSIBLE_DIRECTORY=true`
* `ALLOW_DIRECTORY_LIST=false`
* `PROVIDE_INDEX_PAGE=true`
Are set, requests containing query strings without a trailing slash were being duplicated (`foo?a=b` were becoming `foo?a=b?a=b`).
The `rewrite` directive will automatically append the query string unless a final trailing `?` is supplied. This was causing the duplication
Added an explanatory comment and a trailing `?` to the rewrite rule to prevent automatic appending of the query string as we already do it in the argument to the rewrite rule.
I chose to do this rather than depending on the default behavior of `rewrite` since the rule as it is expressed is more explicit.  The trailing `?` is mysterious and so …
=> fix: Solve an issue where rewrites due to APPEND_SLASH_FOR_POSSIBLE_DIRECTORY would cause duplication of the query string

standalone_ubuntu_oss_install.sh
we added support of IMDSv2 to the EC2 check with a fall back to IMDSv1,
also, some nginx env declarations were moved from the environment file to the nginx.conf file
=> Issue #206 -ec2 check to support IMDSv1 and IMDSv2 + moving env vars to conf file

test.sh
njs will be deprecating the `-t` command in its CLI tool. This change uses the `-m` flag to indicate a module instead of `-t`.
=> Move latest-njs testing to the -m module for forwards compatibility

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/pull_request_template.md, CODE_OF_CONDUCT.md, CONTRIBUTING.md, LICENSE, README.md, SECURITY.md, SUPPORT.md
Notable differences:
- Add a PR template
- Update Code of Conduct
- Add Contributing link and Copyright notice to README
- Remove Docker pulls vanity metric (vanity metrics are meh) from README
- Minor updates throughout all the community related docs to bring the docs up to speed with the latest community doc guidelines
=> docs: update community related docs

.github/workflows/f5-cla.yml
Remove the beta identifier from the signatures path and do a few minor style updates.
Before creating a PR, run through this checklist and mark each as complete:
=> chore: F5 CLA workflow is out of beta

Dockerfile.buildkit.plus, Dockerfile.plus
Dependabot will not generate PRs for Dockerfiles that include a build argument within their FROM instruction. This PR fixes that issue.
Before creating a pull request (PR), run through this checklist and mark each as complete:
=> ci(fix): Properly auto-update Dockerfiles using a build arg

common/etc/nginx/nginx.conf
"AWS_CONTAINER_CREDENTIALS_RELATIVE_URI" is set when "00-check-for-required-env.sh" runs. In "awscredentials.js" -> "fetchCredentials", however, the "AWS_CONTAINER_CREDENTIALS_RELATIVE_URI" is not set anymore and erroneously, "_fetchEC2RoleCredentials" instead of "_fetchEcsRoleCredentials" is called.
Describe the use case and detail of the change. If this PR addresses an issue on GitHub, make sure to include a link to that issue using one of the [supported keywords](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue) in this PR description (not in the title of the PR).
Before creating a pull request (PR), run through this checklist and mark each as complete:
=> fix: Preserve AWS_CONTAINER_CREDENTIALS_RELATIVE_URI in nginx.conf

oss/etc/nginx/templates/upstreams.conf.template, plus/etc/nginx/templates/upstreams.conf.template
This change unifies the OSS upstream configuration with the Plus upstream configuration, so that both are using dynamic DNS reconfiguration for upstreams.
Before creating a pull request (PR), run through this checklist and mark each as complete:
=> feat: use dynamic dns resolution for upstreams in oss like plus

Dockerfile.buildkit.plus, Dockerfile.plus
This makes sure all keys are exported to a keyring archive, as opposed to only the first key.
=> fix: Pass GPG key ids as separate arguments when exporting.
